# 난수 생성 함수
random

In [2]:
import numpy as np

In [3]:
a = np.random.rand(2,2) # 0 ~ 1 사이에 값 랜덤
print(a)

[[0.9477654  0.02384224]
 [0.27556398 0.85426032]]


In [4]:
b = np.random.randn(2,2) # 평균이 0, 분산이 1: 표준 정규 분포
print(b)

[[ 0.54946851 -0.31191518]
 [ 2.13986151 -1.36211129]]


In [5]:
c = np.random.randint(0,10, size=5) # 랜덤한 정수값 생성
print(c)

[4 1 3 1 0]


In [7]:
c2 = np.random.randint(0,10, size=(2,2))
print(c2)

[[6 8]
 [4 1]]


In [8]:
d = np.arange(5)
np.random.shuffle(d) #복사본 새성이 x 원본값 변함
print(d)

[2 4 3 0 1]


In [9]:
# choice = np.random.choice(d,5) #중복을 허용
# choice = np.random.choice(d,5,replace=False) #중복 허용 x
choice = np.random.choice(d, 5, p = [0,0.4,0.2, 0.3, 0.1])
#p값을 100% 로 설정
print(choice)

[4 4 4 0 3]


In [10]:
#permutation 순열 -> 수정해서 파일 전함
a = np.arange(10)
a_p = np.random.permutation(a)
print(a_p)
print(a)

[0 6 5 4 7 1 2 9 8 3]
[0 1 2 3 4 5 6 7 8 9]


In [11]:
#정규분포를 따르는 난수 생성
# a = np.random.normal('평균','표준편차','갯수')
a = np.random.normal(0,1,3)
print(a)

[0.17344046 0.83658089 1.00027958]


# pandas
- 데이터 자체를 분석, 파악
- 표
- 데이터 다루는 데 초점
- 정렬, 필터링, 그룹화, 집계

- 데이터 로딩 및 저장
- 데이터 인덱싱 및 슬라이싱
- 결측치 처리
- 데이터 변환
- 데이터 집계 및 그룹화
---
- 시계열 데이터 처리
- 데이터 시각화

# Series 시리즈
- 인덱스 지정 가능


In [12]:
import pandas as pd

In [13]:
s = pd.Series([1,2,3,4]) # 리스트
print(s)

0    1
1    2
2    3
3    4
dtype: int64


In [14]:
s2 = pd.Series({'a':1, 'b':2, 'c':3, 'd':4}) #딕셔너리
print(s2)

a    1
b    2
c    3
d    4
dtype: int64


In [15]:
s3 = pd.Series(5, index=[0,1,2]) #스칼라
print(s3)

0    5
1    5
2    5
dtype: int64


In [16]:
data = [1,2,3,4,5]
index = ['a','b','c','d','e']
series = pd.Series(data, index=index)
print(series)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [17]:
s = pd.Series(data)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64


# 슬라이싱

In [18]:
data = [1,2,3,4,5]
series = pd.Series(data)

In [19]:
series[0]

1

In [20]:
series[0:4]

0    1
1    2
2    3
3    4
dtype: int64

In [21]:
series[:4]

0    1
1    2
2    3
3    4
dtype: int64

In [22]:
series[::-1]

4    5
3    4
2    3
1    2
0    1
dtype: int64

# boolean indexing

In [23]:
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [24]:
print(series > 2)

0    False
1    False
2     True
3     True
4     True
dtype: bool


In [25]:
series[series > 2] # a[a조건]

2    3
3    4
4    5
dtype: int64

In [26]:
# 5보다 작은 시리즈 만들기
print(series[series < 5])

0    1
1    2
2    3
3    4
dtype: int64


# series 산술연

In [27]:
print(series + 100)
print(series - 100)
print(series * 100)
print(series ** 100)
print(series / 100)
print(series % 100)
print(series // 100)
# 곱하기: *, 제곱: **, 나누기(float 몫): /, 나머지: %, 나누기(int 몫): //

0    101
1    102
2    103
3    104
4    105
dtype: int64
0   -99
1   -98
2   -97
3   -96
4   -95
dtype: int64
0    100
1    200
2    300
3    400
4    500
dtype: int64
0                      1
1                      0
2   -2984622845537545263
3                      0
4   -3842938066129721103
dtype: int64
0    0.01
1    0.02
2    0.03
3    0.04
4    0.05
dtype: float64
0    1
1    2
2    3
3    4
4    5
dtype: int64
0    0
1    0
2    0
3    0
4    0
dtype: int64


# series 객체에 접근
- keys - > index
- values

In [28]:
print(series.keys)

<bound method Series.keys of 0    1
1    2
2    3
3    4
4    5
dtype: int64>


In [29]:
print(series.keys())
print(series.index)
print(series.values)

RangeIndex(start=0, stop=5, step=1)
RangeIndex(start=0, stop=5, step=1)
[1 2 3 4 5]


In [30]:
series[0]

1

In [31]:
s2 = pd.Series({'a': 1, 'b':2, 'c':3, 'd': 4}) # 딕셔너리
print(s2.keys())

Index(['a', 'b', 'c', 'd'], dtype='object')


In [32]:
s2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [33]:
print(s2)

a    1
b    2
c    3
d    4
dtype: int64


In [34]:
# items

print(s2.items()) # zip -> 순회가 가능, 쌍

In [35]:
for index, value in s2.items():
  print(f'인덱스 {index}, 데이터 : {value}')

인덱스 a, 데이터 : 1
인덱스 b, 데이터 : 2
인덱스 c, 데이터 : 3
인덱스 d, 데이터 : 4


In [36]:
s = pd.Series([10,20,30,40], index=['a','b','c','d'])

In [37]:
print(s)

a    10
b    20
c    30
d    40
dtype: int64


In [38]:
print(s.loc['b']) # loc: 행에 접근 -> 레이블(특정 인덱스)에 접근하기 위해서 -> 슬라이싱 범위 다포
print(s.loc['b':'d'])

20
b    20
c    30
d    40
dtype: int64


In [39]:
print(s.iloc[1]) # iloc : 행에기반한 열에 접근

20


In [40]:
s.iloc[-1]

40

In [41]:
print(s.at['a']) # at loc 비슷, 하나의 값만 가져올 때

10


In [42]:
print(s.iat[0]) # at 에 기반

10


In [43]:
print(s.get('e', default=-1)) # 없을 때 값 처리 방법이 다름, error가 나지 않고 없다는 걸 알려줌

-1


# 결측값(NaN, None)
- isna()
- isnull()

NaN(Not a Number) -> float
None -> None

In [44]:
data = [1,2,3,None]
print(np.array(data))

[1 2 3 None]


In [46]:
s= pd.Series(data)

In [47]:
s.isna()


0    False
1    False
2    False
3     True
dtype: bool

In [49]:
s.isnull().sum()

1

In [50]:
#결측치 제거

s.dropna()

0    1.0
1    2.0
2    3.0
dtype: float64

In [51]:
#0으로 치환
s.fillna(0)

0    1.0
1    2.0
2    3.0
3    0.0
dtype: float64

# series 함수

In [52]:
s = pd.Series([1,3,5,7,9])

In [53]:
s.count()

5

In [54]:
s.min()

1

In [55]:
s.max()

9

In [56]:
print(s.mean())
print(s.median())
print(s.std())
print(s.var())

5.0
5.0
3.1622776601683795
10.0


In [57]:
s.describe()

count    5.000000
mean     5.000000
std      3.162278
min      1.000000
25%      3.000000
50%      5.000000
75%      7.000000
max      9.000000
dtype: float64

NameError: ignored