#1 array()
- 차원별 배열 생성


In [4]:
import numpy as np

In [5]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

[1 2 3 4 5]


In [6]:
arr_1d = np.array([i for i in range(1,10,2)])
print(arr_1d)

[1 3 5 7 9]


In [7]:
print(np.array(range(10)))
print(np.array(range(1,11)))
print(np.array(range(2,10,2)))
print(np.array(range(10,2,-1)))

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[2 4 6 8]
[10  9  8  7  6  5  4  3]


In [8]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [9]:
b = np.array([[1,2],[3,4],[5,6]])
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
print(b) 
print(b.shape) #배열 축의 크기
print(b.ndim) #배열의 차원
print(b.dtype) #배열의 데이터 타입
print(b.itemsize) # 각 요소의 바이트 단위 크기
print(b.nbytes)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
2
int64
8
48


In [12]:
# 3차원

c = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(c) 
print(c.shape) #배열 축의 크기
print(c.ndim) #배열의 차원
print(c.dtype) #배열의 데이터 타입
print(c.itemsize) # 각 요소의 바이트 단위 크기
print(c.nbytes)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
3
int64
8
64


In [19]:
# 하나의 숫자값 : 스칼라

s = np.array(1)
print(s)

1


In [14]:
# 1 차원 벡터
v = np.array([1,2,3])
print(v)

[1 2 3]


In [15]:
#3 차원 텐서
t = np.array([[[1,2],[1,2]], [[1,2],[1,2]]])
print(t)

[[[1 2]
  [1 2]]

 [[1 2]
  [1 2]]]


In [16]:
# for 문을 이용해서 배열 생성

f = np.array([i for i in range(0,10,2)]) #(start, end, step)

In [17]:
print(f)

[0 2 4 6 8]


In [21]:
print(f.ndim)
print(f.shape)
print(f.dtype)
print(f.itemsize)
print(f.nbytes)

1
(5,)
int64
8
40


## 데이터 타입

1. 숫자형
2. 문자형
3. 논리형

### 숫자형

- 부호가 있는 정수(Signed integer)
- 부호가 없는 정수(Unsigned integer)
- 실수(floating point)
- 복소수(complex)

In [22]:
# int (8bit, 16bit, 32bit, 64bit)

data = [1.1,2,3]
i = np.array(data, dtype=np.int32)
print(i)

[1 2 3]


In [24]:
data2 = [-1, 2,3]

ui = np.array(data2, dtype=np.uint32) # uint 8, 16, 32(0~4,294,967,295), 64
print(ui)

[4294967295          2          3]


In [25]:
f = np.array(data, dtype=np.float64)
print(f)

[1.1 2.  3. ]


In [26]:
c = np.array([1 + 2j, 3+2j, 5+2j], dtype=np.complex64)

In [27]:
print(c.real) #실수
print(c.imag) # 허수

[1. 3. 5.]
[2. 2. 2.]


## 문자형

- string_
- unicod_

In [28]:
data = [1,2,3]
s = np.string_(data)
print(s)

b'\x01\x02\x03'


In [29]:
print(s.dtype)

|S3


In [30]:
data3 = [1, 2, 3, 4, 5]

# string_
s2 = np.string_(data3) # s2_ = np.array(data3, dtype='S')
# print, 그 자체, 데이터 타입
print(s2)
print(s2.dtype)

b'\x01\x02\x03\x04\x05'
|S5


In [31]:
u = np.array(data3, dtype='U') #unicode

print(u)
print(u.dtype)

['1' '2' '3' '4' '5']
<U1


In [32]:
data4 = [11, 22, 33, 44, 55]

u2 = np.array(data4, dtype='U')
print(u2)
print(u2.dtype)

['11' '22' '33' '44' '55']
<U2


## 논리형 (boolean)

- True(1), False(0)
- 비트 연산 사용: & and, | or, ^ xor, ~ not

In [34]:
l1 = np.array([True, False, True])
l2 = np.array([False, True, False])

print(l1.dtype)
print(l2.dtype)

bool
bool


In [35]:
and_ = np.logical_and(l1, l2)
print(and_)

[False False False]


## 데이터 형 변환 (Cast, Casting 형 변환)

- 데이터들끼리 형태를 맞춰줌
- 예시) 이미지 데이터 -> uint형으로 불러옴 -> float

In [37]:
data = [1.9,2,3]
a = np.float64(data) #np.데이터 타입
print(a)
print(a.dtype)

[1.9 2.  3. ]
float64


In [38]:
a = a.astype(np.int64)
print(a)
print(a.dtype)

[1 2 3]
int64


In [39]:
b = np.uint16(0)
print(b)
print(b.dtype)

0
uint16


In [40]:
print(b)
print(b.dtype) #파이썬에서 자동 연산

0
uint16


In [41]:
c = np.uint16(-1) # uint( 0 ~ 65,535)
print(c)

65535


## 산술 연산

In [44]:
data = [[1,2,3], [4,5,6]]
data2 = [[1,1,1], [2,2,2]]

In [46]:
print(len(data))
print(len(data[0]))

2
3


In [47]:
len(data2)

2

In [48]:
data = [[1,2,3], [4,5,6]]

In [49]:
sum = 0

for i in range(len(data)):
  for j in range(len(data[0])): # 0 1 2
    sum += data[i][j]
print(sum)
#data[j]

21


In [50]:
a = np.array([1,2,3])
b = np.array([4,5,6])

#사칙연산

sum = a+ b
min = a-b
mul = a * b
div = a / b

print(sum)
print(min)
print(mul)
print(div)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [51]:
a = np.array([1,2,3])
b = np.array([4,5,6])

aa = np.exp(a) #지수 함수

print(aa)

[ 2.71828183  7.3890561  20.08553692]


In [52]:
bb = np.log(b) # 자연로그
print(bb)

[1.38629436 1.60943791 1.79175947]


In [53]:
cc= np.log2(b) # 밑이 2인 로그
print(cc)

[2.         2.32192809 2.5849625 ]


In [54]:
d = np.array([0, np.pi/2, np.pi])

sin_ = np.sin(d)

cos_ = np.cos(d)

tan_ = np.tan(d)

print(sin_)
print(cos_)
print(tan_)

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


# 배열의 연결과 분할

In [55]:
print( 'a' + 'b')

ab


In [56]:
x = [1,2,3]
y = [4,5,6]

In [58]:
concat = np.concatenate([x,y])
print(concat)
print(concat.dtype)

[1 2 3 4 5 6]
int64


In [59]:
x2 = [[1,2],[3,4]]
y2 = [[4,5],[6,7]]

concat2 = np.concatenate([x2,y2], axis=1) #열 병합 
concat3 = np.concatenate([x2,y2], axis=0) #행 병합

print(concat2)
print(concat3)

[[1 2 4 5]
 [3 4 6 7]]
[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [60]:
print(x2)

[[1, 2], [3, 4]]


In [61]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [62]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [63]:
arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [64]:
x2 = [[1, 2], [3, 4]] # 2x2
y2 = [[4, 5], [6, 7]] # 2x2


h = np.hstack([x2, y2])
print(h)

[[1 2 4 5]
 [3 4 6 7]]


In [65]:
x2 = [[1, 2], [3, 4]] # 2x2
y2 = [[4, 5], [6, 7]] # 2x2


v = np.vstack([x2, y2])
print(v)

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [69]:
x2 = np.array(
   [[1, 2],
    [3, 4],
    [5, 6]])

h2 = np.hsplit(x2, 2)
print(h2)
print(x2.shape)

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]])]
(3, 2)


In [70]:
x2 = np.array(
   [[1, 2],
    [3, 4],
    [5, 6]])

v2 = np.vsplit(x2, 3)
print(x2.shape)
print(v2)

(3, 2)
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


# 다양한 배열 만들기

In [72]:
zero = np.zeros([3,4])

In [73]:
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [76]:
one = np.ones([3,4])
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [77]:
eye = np.eye(4)
print(eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 넘파이 제공 함수

In [78]:
arr1 = np.array([-1, -2, -3, -4])

abs_arr = np.abs(arr1)
print(abs_arr)

[1 2 3 4]


In [79]:
arr2 = np.array([1,4,9,16])
sqrt_arr = np.sqrt(arr2)
print(sqrt_arr)

[1. 2. 3. 4.]


## 집계함수

In [80]:
a = np.array([1,2,3,4,5])
a_mean = np.mean(a)
print(a_mean)

3.0


In [81]:
b = np.array([1,3,5,7,9])
b_median = np.median(b)
print(b_median)

5.0


In [82]:
c = np.array([1,2,3,4,5])
c_std = np.std(c)
print(c_std)

1.4142135623730951


In [83]:
d = np.array([1,2,3,4,5])
d_var = np.var(d)
print(d_var)

2.0


In [84]:
d = np.array([1,2,3,4,5])
d_sum = np.sum(d)
print(d_sum)

15


In [85]:
d_cumsum = np.cumsum(d)
print(d_cumsum)

[ 1  3  6 10 15]


In [87]:
min = np.argmin(d)
print(min)
print(d[min])

0
1


In [88]:
max = np.argmax(d)
print(max)
print(d[max])

4
5


In [89]:
a = np.array([1,1,1,1]) #배열 안에 하나라도 true 가 있는지

a_true = np.any(a)
print(a_true)

True


In [90]:
a_all = np.all(a) #전부다 트루인지
print(a_all)

True


In [91]:
a = np.array([1,2, np.nan, 4])
a_nsum = np.nansum(a)
print(a_nsum)

7.0


In [92]:
a_sum = np.sum(a)
print(a_sum)

nan


In [93]:
d = np.array([1,2,3,4,5])
con = np.where(d < 3 , d, 0)
con1 = np.where(d<3)
print(con)
print(con1)

[1 2 0 0 0]
(array([0, 1]),)


### Boolean Indexing

조건에 따른 요소들을 판별해서 새로운 배열을 만든다.

In [94]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

even_a = a[a % 2 == 0]
print(even_a)
print(a)

[ 2  4  6  8 10]
[ 1  2  3  4  5  6  7  8  9 10]


### Broadcast(브로드캐스트)

- 크기가 다른 배열 간의 연산도 가능하게 해줌
- ex) 1차원, 2차원

- 두 배열의 차원 수가 다를 경우, 더 작은 차원의 배열에 큰 차원의 배열이 맞을 때까지 1을 추가한다.
- 두 배열의 차원 수가 같을 경우에도, 크기가 1인 차원이 있다면 다른 배열의 크기와 일치하도록 복제된다.
- 두 배열의 차원 수가 같을 경우에도, 모든 차원의 크기가 같거나 크기가 1이라면 모양이 같은 두 배열의 요소 간 연산을 한다.

In [95]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
print(c)

[5 7 9]


In [96]:
d = np.array([[1],[2],[3]])
e = np.array([4,5,6])
f = d + e

In [98]:
print(f)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [99]:
d = np.array([[1], [2], [3]])
e = np.array([[4, 5, 6]])

f = d + e
print(f)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
#문제.1 주어진 여러 개의 1차원 배열을 연결하여 하나의 큰 1차원 배열로 반환하세요.

In [105]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9, 10])

# concat 함수

arr_a = np.concatenate([arr1, arr2, arr3], axis= 0)

In [106]:
arr_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
#4.2 주어진 2차원 배열에서 각 열의 평균값을 계산하여 새로운 1차원 배열로 나타내세요.
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])


arr_mean = np.mean(arr)

In [108]:
print(arr_mean)

5.0


In [113]:
arr_mean = np.mean(np.hsplit(arr,3))
print(arr_mean)

5.0


In [143]:
#정답
arr_mean = np.mean(arr, axis=0)
print(arr_mean)

3.0


In [144]:
# 4.2 정답


print(np.mean(arr, axis=0) )

3.0



In [111]:
print(arr_1)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


4.3 주어진 2차원 배열에서 각 행의 최대값을 구하여 1차원 배열로 반환하세요.

In [115]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

arr_max = np.argmax(arr)

In [116]:
print(arr_max)


8


In [121]:
#정답
arr_max = np.max(arr, axis=1)
print(arr_max)

[3 6 9]


4.4 0에서 1사이의 값으로 크기 10개의 1차원 배열을 만들어주세요.

In [145]:
np.linespace(0,1,10)

AttributeError: ignored

In [122]:
num = np.arange(0,1,0.1)

In [123]:
print(num)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


4.5 주어진 1차원 배열에서 짝수인 요소들의 합을 계산하는 함수 sum_of_evens를 작성하세요.

- 
def sum_of_evens(arr: np.ndarray) -> int:

In [125]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

sum_of_evens = np.sum(arr[ arr % 2 ==0])

print(sum_of_evens)
# print(sum_of_evens(arr))

30


4.6 수평분할, 수직분할, 수평 스택, 수직 스택 문제를 풀어봅시다.

In [126]:
# 분할할 배열 생성
arr = np.arange(1, 13).reshape((3, 4))
print("원본 배열:")
print(arr)

원본 배열:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [129]:
arr_h = np.hsplit(arr,4)
print(arr_h)
arr_re = np.hstack(arr_h)
print(arr_re)

[array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]]), array([[ 4],
       [ 8],
       [12]])]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [130]:
arr_v = np.vsplit(arr,3)
print(arr_v)
arr_re = np.vstack(arr_v)
print(arr_re)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


4.7 배열에서 조건에 맞는 값 반환하는 문제를 풀어봅시다.

In [135]:
# 조건 : 값을 10으로 나누었을 때 나머지가 0이면 원래 값 출력, 아니면 0으로 출력하세요.
arr = np.arange(0, 100, 5).reshape((5,4))
arr_new = np.where(arr % 10 == 0,arr,0)
print(arr_new)

[[ 0  0 10  0]
 [20  0 30  0]
 [40  0 50  0]
 [60  0 70  0]
 [80  0 90  0]]


4.8 [3x3]배열 lst 중 짝수만 뽑아내는 부울린 인덱싱 배열(numpy 배열)을 사용하여 짝수 배열 n 을 만드시오

In [136]:
lst = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
a = np.array(lst)

In [137]:
lst_even = a[a % 2 == 0]
print(lst_even)

[2 4 6 8]


4.9 각도를 이용해서 삼각함수를 만들어봅시다.

In [139]:
angle = np.pi / 3 # 라디안 표기 = 60도 
# 360도는 2라디안 으로, 180도는 1라디안으로 표현합니다.

a = np.sin(angle)

b = np.cos(angle)

c= np.tan(angle)

In [140]:
a

0.8660254037844386

4.10 조건함수를 사용해서  짝수조건을 만족하는 요소의 값이 2배로 만드는 배열을 만드시오.

In [141]:
arr = np.array([1, 2, 3, 4, 5])

In [142]:
arr_even = np.where(arr % 2 ==0, arr*2, arr)
print(arr_even)

[1 4 3 8 5]


In [ ]:
a